### ISSUE TITLE
Crash durante il caricamento dei settings

### ISSUE THREAD

**Issue by aaaasmile** [aaaasmile/CuperativaJs#1]
Versione 1.2.9.
Questo è il call stack:
`
Program aborted on syntax error on line 139, col -1:`'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/ruby_0_0_1/ruby/lib/ruby/1.8/yaml.rb:133:in `load'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/ruby_0_0_1/ruby/lib/ruby/1.8/yaml.rb:133:in`load'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/ruby_0_0_1/ruby/lib/ruby/1.8/yaml.rb:144:in `load_file'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/ruby_0_0_1/ruby/lib/ruby/1.8/yaml.rb:143:in`open'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/ruby_0_0_1/ruby/lib/ruby/1.8/yaml.rb:143:in `load_file'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/1_2_9/app/src/cuperativa_gui.rb:462:in`load_application_settings'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/1_2_9/app/src/cuperativa_gui.rb:172:in `initialize'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/1_2_9/app/src/start_cuperativa.rb:18:in`new'
C:/Users/Nazzareno/AppData/Local/invido_it/Cuperativa/1_2_9/app/src/start_cuperativa.rb:18
'

Sembra che il file yaml non sia in ordine, la funzione load_application_settings deve avere un error handling ed ignorare i settings che non si lasciano caricare.

**Comment by aaaasmile** [comment]
Pubblicata la versione 1.2.10 di CuperativaSoloRuby che risolve il problema.
